name: Test Inputs with Custom Action
on:
  workflow_dispatch:
    inputs:
      stream:
        type: choice
        description: Select the stream
        required: true
        options:
          - dev2
          - dev1
          - int2
          - int1
          - prod
          - test1
          - test2

jobs:
  DetermineCluster:
    runs-on: ubuntu-latest
    outputs:
      cluster: ${{ steps.publish.outputs.result }}
    steps:
      - name: Determine Cluster
        id: determineCluster
        uses: Lordi999/GHA-E9/.github/actions/determineCluster@main
        with:
          environment: ${{ inputs.stream }}
      - name: Set Output
        id: setOutput
        run: echo "result=${{ steps.determineCluster.outputs.cluster }}" >>  $GITHUB_OUTPUT
      
  OutputCluster:
    needs: DetermineCluster
    runs-on: ubuntu-latest
    steps:
      - name: Output Result
        run: echo ${{ needs.DetermineCluster.outputs.cluster }}