name: Deploy X Service
on:
  workflow_dispatch:
    inputs:
      stream:
        type: choice
        description: Select the stream
        required: true
        options:
          - dev2
          - dev1
          - int2
          - int1
          - prod

jobs:
  GetCluster:
    runs-on: ubuntu-latest
    outputs:
      cluster: ${{ steps.determine.outputs.cluster }}
    steps:
      - name: Determine Cluster
        id: determine
        run: |
              echo "cluster=dev" >> "$GITHUB_OUTPUT"
             

  OutputCluster:
    needs: GetCluster
    runs-on: ubuntu-latest
    steps:
        - name: Output Stream
          run: echo ${{ inputs.stream }}
        - name: Output Cluster
          run: echo ${{ needs.GetCluster.outputs.cluster }}
     